{application,git_handler_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{git_handler_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[git_handler,lib_git_handler]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
