{application,log2_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{log2_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_db_log2,lib_dbase,lib_log2,log2]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
