{application,main,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{main_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_main,main,main_app,main_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
